[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[deploy]
startCommand = "cd backend && node src/database/init.js && node src/server.js"
