const router = require('express').Router();
const controller = require('../controllers/trabajadorController');
router.get('/', controller.getAll);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
router.post('/calcular-pago', controller.calcularPago);
router.get('/pagos', controller.pagos);
router.put('/pagos/:id/pagar', controller.marcarPagado);
module.exports = router;
